FROM python:3.10
LABEL authors="juliofgx"

RUN apt-get update

# Install Vosk and its dependencies
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install speechbrain

# Set the working directory inside the container
WORKDIR /workdir

# Copy your script (let's assume it's named your_script.py) into the container
COPY speechbrain_asr.py /workdir/transcript.py
COPY keep_alive.py /workdir/keep_alive.py

RUN mkdir -p /volume

ENTRYPOINT ["python", "keep_alive.py"]