# Use a base Python image
FROM python:3.10.12

# Set working directory
WORKDIR /workdir
COPY seamless_asr.py /workdir/transcript.py
# Update and install necessary packages
RUN apt-get update
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install --quiet git+https://github.com/huggingface/transformers sentencepiece
RUN pip install --quiet datasets
RUN pip install protobuf
RUN pip install soundfile
RUN pip install librosa

COPY keep_alive.py /workdir/keep_alive.py

RUN mkdir -p /volume

ENTRYPOINT ["python", "keep_alive.py"]