FROM python:3.10
LABEL authors="juliofgx"

RUN apt-get update && apt-get install -y ffmpeg
RUN pip install --upgrade pip
RUN pip install --upgrade git+https://github.com/huggingface/transformers.git accelerate

# Set the working directory inside the container
WORKDIR /workdir

# Copy your script (let's assume it's named your_script.py) into the container
COPY whisper_asr.py /workdir/transcript.py
COPY keep_alive.py /workdir/keep_alive.py

RUN mkdir -p /volume

ENTRYPOINT ["python", "keep_alive.py"]