# Use a base Python image
FROM python:3.10.12

# Set working directory
WORKDIR /workdir

# Update and install necessary packages

RUN apt-get update
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN apt-get update && apt-get install -y libsndfile1 ffmpeg
RUN pip install Cython
RUN pip install nemo_toolkit['all']


COPY nemo_asr.py /workdir/transcript.py
COPY keep_alive.py /workdir/keep_alive.py

RUN mkdir -p /volume

ENTRYPOINT ["python", "keep_alive.py"]