FROM pytorch:latest
LABEL authors="juliofgx"

RUN apt-get update


# Set the working directory inside the container
WORKDIR /workdir

# Copy your script (let's assume it's named your_script.py) into the container
COPY torch_asr.py /workdir/transcript.py
COPY keep_alive.py /workdir/keep_alive.py

RUN mkdir -p /volume

ENTRYPOINT ["python", "keep_alive.py"]